// <auto-generated />
using System;
using FinMate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinMate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinMateDbContext))]
    [Migration("20260911075903_CreateGamificationTables")]
    partial class CreateGamificationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinMate.Domain.Entities.AiResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<long?>("BalanceAfterCents")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_cents");

                    b.Property<double?>("CategorizationConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("categorization_confidence");

                    b.Property<string>("CategorizerVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("categorizer_version");

                    b.Property<string>("CategorySlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_slug");

                    b.Property<double?>("ClassifierConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("classifier_confidence");

                    b.Property<string>("ClassifierLabel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classifier_label");

                    b.Property<string>("ClassifierVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classifier_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DuplicateRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_request_id");

                    b.Property<double?>("ExtractionConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("extraction_confidence");

                    b.Property<string>("ExtractorVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extractor_version");

                    b.Property<bool>("IsPotentialDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_potential_duplicate");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_name");

                    b.Property<Guid>("NotificationLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_log_id");

                    b.Property<string>("PipelineResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pipeline_result");

                    b.Property<int?>("ProcessingMs")
                        .HasColumnType("integer")
                        .HasColumnName("processing_ms");

                    b.Property<DateTimeOffset?>("TransactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transacted_at");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("NotificationLogId")
                        .IsUnique()
                        .HasDatabaseName("uq_ai_results_notification_log_id");

                    b.ToTable("ai_results", null, t =>
                        {
                            t.HasCheckConstraint("chk_ai_results_pipeline_result", "pipeline_result IN ('financial','non_financial','uncertain','extraction_failed','error')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("LimitCents")
                        .HasColumnType("bigint")
                        .HasColumnName("limit_cents");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "PeriodType")
                        .IsUnique()
                        .HasDatabaseName("uq_budgets_user_total")
                        .HasFilter("category_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("UserId", "CategoryId", "PeriodType")
                        .IsUnique()
                        .HasDatabaseName("uq_budgets_user_category")
                        .HasFilter("category_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("budgets", null, t =>
                        {
                            t.HasCheckConstraint("chk_budgets_limit_cents", "limit_cents > 0");

                            t.HasCheckConstraint("chk_budgets_period_type", "period_type IN ('monthly')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.BudgetPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("Alert100SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alert_100_sent_at");

                    b.Property<DateTimeOffset?>("Alert80SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alert_80_sent_at");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("LimitCents")
                        .HasColumnType("bigint")
                        .HasColumnName("limit_cents");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<long>("SpentCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("spent_cents");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PeriodEnd")
                        .HasDatabaseName("idx_budget_periods_period_end");

                    b.HasIndex("BudgetId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("uq_budget_periods_budget_start");

                    b.ToTable("budget_periods", (string)null);
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon_name");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_categories_system_slug")
                        .HasFilter("user_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("UserId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_categories_user_slug")
                        .HasFilter("user_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("FinMate.Domain.Entities.DailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("summary_date");

                    b.Property<Guid?>("TopCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("top_category_id");

                    b.Property<long>("TopCategorySpentCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("top_category_spent_cents");

                    b.Property<long>("TotalIncomeCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_income_cents");

                    b.Property<long>("TotalSpentCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_spent_cents");

                    b.Property<int>("TransactionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("transaction_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TopCategoryId");

                    b.HasIndex("UserId", "SummaryDate")
                        .IsUnique()
                        .HasDatabaseName("uq_daily_summaries_user_date");

                    b.ToTable("daily_summaries", (string)null);
                });

            modelBuilder.Entity("FinMate.Domain.Entities.DataDeletionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset>("ScheduledHardDeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_hard_delete_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledHardDeleteAt")
                        .HasDatabaseName("idx_data_deletion_requests_scheduled_hard_delete_at");

                    b.ToTable("data_deletion_requests", null, t =>
                        {
                            t.HasCheckConstraint("chk_data_deletion_requests_status", "status IN ('pending','processed')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<long>("BalanceCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("balance_cents");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsMonitored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_monitored");

                    b.Property<string>("PackageName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("package_name");

                    b.Property<Guid?>("ProviderConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_config_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConfigId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_financial_accounts_user_id");

                    b.HasIndex("UserId", "PackageName")
                        .IsUnique()
                        .HasDatabaseName("uq_financial_accounts_user_package")
                        .HasFilter("package_name IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("financial_accounts", null, t =>
                        {
                            t.HasCheckConstraint("chk_financial_accounts_account_type", "account_type IN ('bank','ewallet','cash')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.MascotItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_premium");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("UnlockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unlock_level");

                    b.Property<string>("UnlockMissionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unlock_mission_code");

                    b.Property<string>("UnlockType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unlock_type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_mascot_items_code");

                    b.ToTable("mascot_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_mascot_items_item_type", "item_type IN ('hat','outfit','accessory','background')");

                            t.HasCheckConstraint("chk_mascot_items_unlock_payload", "(unlock_type = 'default' AND unlock_level IS NULL AND unlock_mission_code IS NULL) OR (unlock_type = 'level' AND unlock_level IS NOT NULL) OR (unlock_type = 'mission' AND unlock_mission_code IS NOT NULL)");

                            t.HasCheckConstraint("chk_mascot_items_unlock_type", "unlock_type IN ('default','level','mission')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("ConditionTarget")
                        .HasColumnType("integer")
                        .HasColumnName("condition_target");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("condition_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("ExpReward")
                        .HasColumnType("integer")
                        .HasColumnName("exp_reward");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_missions_code");

                    b.ToTable("missions", null, t =>
                        {
                            t.HasCheckConstraint("chk_missions_condition_target", "condition_target > 0");

                            t.HasCheckConstraint("chk_missions_exp_reward", "exp_reward >= 0");

                            t.HasCheckConstraint("chk_missions_period_type", "period_type IN ('daily','weekly','one_time')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.UserGamification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStreakDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak_days");

                    b.Property<int>("ExpPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("exp_points");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("last_activity_date");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<int>("LongestStreakDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("longest_streak_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LastActivityDate")
                        .HasDatabaseName("idx_user_gamification_last_activity");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_gamification_user_id");

                    b.ToTable("user_gamification", null, t =>
                        {
                            t.HasCheckConstraint("chk_user_gamification_exp", "exp_points >= 0");

                            t.HasCheckConstraint("chk_user_gamification_level", "level >= 1");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.UserMascotItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsEquipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_equipped");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_type");

                    b.Property<Guid>("MascotItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("mascot_item_id");

                    b.Property<DateTimeOffset>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MascotItemId");

                    b.HasIndex("UserId", "ItemType")
                        .IsUnique()
                        .HasDatabaseName("uq_user_mascot_items_equipped_per_type")
                        .HasFilter("is_equipped");

                    b.HasIndex("UserId", "MascotItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_mascot_items_user_item");

                    b.ToTable("user_mascot_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_user_mascot_items_item_type", "item_type IN ('hat','outfit','accessory','background')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.UserMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("exp_awarded");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId", "PeriodEnd")
                        .HasDatabaseName("idx_user_missions_user_period_end");

                    b.HasIndex("UserId", "MissionId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("uq_user_missions_user_mission_period");

                    b.ToTable("user_missions", (string)null);
                });

            modelBuilder.Entity("FinMate.Domain.Entities.GoalContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<DateTimeOffset>("ContributedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contributed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("SavingGoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("saving_goal_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SavingGoalId", "ContributedAt")
                        .HasDatabaseName("idx_goal_contributions_goal_contributed_at");

                    b.ToTable("goal_contributions", null, t =>
                        {
                            t.HasCheckConstraint("chk_goal_contributions_amount_cents", "amount_cents > 0");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("FinancialAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_account_id");

                    b.Property<string>("NotificationBody")
                        .HasColumnType("text")
                        .HasColumnName("notification_body");

                    b.Property<string>("NotificationTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notification_title");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("package_name");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountId");

                    b.HasIndex("Status", "RetryCount")
                        .HasDatabaseName("idx_notification_logs_status_retry_count");

                    b.HasIndex("UserId", "ContentHash")
                        .HasDatabaseName("idx_notification_logs_user_content_hash");

                    b.ToTable("notification_logs", null, t =>
                        {
                            t.HasCheckConstraint("chk_notification_logs_status", "status IN ('pending','processed','failed','ignored')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.ProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("package_name");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PackageName")
                        .IsUnique()
                        .HasDatabaseName("uq_provider_configs_package_name");

                    b.HasIndex("ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("uq_provider_configs_provider_key");

                    b.ToTable("provider_configs", null, t =>
                        {
                            t.HasCheckConstraint("chk_provider_configs_account_type", "account_type IN ('bank','ewallet')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FinMate.Domain.Entities.SavingGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<DateTimeOffset?>("DeadlineNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_notified_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("SavedCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("saved_cents");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<long>("TargetCents")
                        .HasColumnType("bigint")
                        .HasColumnName("target_cents");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_saving_goals_user_id");

                    b.ToTable("saving_goals", null, t =>
                        {
                            t.HasCheckConstraint("chk_saving_goals_status", "status IN ('active','completed','cancelled')");

                            t.HasCheckConstraint("chk_saving_goals_target_cents", "target_cents > 0");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.SpendingInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InsightType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("insight_type");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_spending_insights_user_created_at");

                    b.HasIndex("UserId", "InsightType", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("uq_spending_insights_user_type_period")
                        .HasFilter("category_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("UserId", "InsightType", "CategoryId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("uq_spending_insights_user_type_category_period")
                        .HasFilter("category_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("spending_insights", null, t =>
                        {
                            t.HasCheckConstraint("chk_spending_insights_insight_type", "insight_type IN ('vs_last_month','recurring_detected','unusual_spending')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<long?>("BalanceAfterCents")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_cents");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_account_id");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_name");

                    b.Property<Guid?>("NotificationLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_log_id");

                    b.Property<Guid?>("SavingGoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("saving_goal_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("TransactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transacted_at");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_transactions_category_id");

                    b.HasIndex("FinancialAccountId")
                        .HasDatabaseName("idx_transactions_financial_account_id");

                    b.HasIndex("NotificationLogId")
                        .IsUnique();

                    b.HasIndex("SavingGoalId");

                    b.HasIndex("UserId", "TransactedAt", "Id")
                        .HasDatabaseName("idx_transactions_user_transacted_at");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("chk_transactions_source", "source IN ('notification','manual')");

                            t.HasCheckConstraint("chk_transactions_status", "status IN ('draft','confirmed')");

                            t.HasCheckConstraint("chk_transactions_transaction_type", "transaction_type IN ('debit','credit')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("uq_users_google_id")
                        .HasFilter("google_id IS NOT NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_role", "role IN ('user','admin')");
                        });
                });

            modelBuilder.Entity("FinMate.Domain.Entities.AiResult", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.NotificationLog", "NotificationLog")
                        .WithOne("AiResult")
                        .HasForeignKey("FinMate.Domain.Entities.AiResult", "NotificationLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationLog");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Budget", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.BudgetPeriod", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.Budget", "Budget")
                        .WithMany("Periods")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Category", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.DailySummary", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.Category", "TopCategory")
                        .WithMany()
                        .HasForeignKey("TopCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.FinancialAccount", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.ProviderConfig", "ProviderConfig")
                        .WithMany()
                        .HasForeignKey("ProviderConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany("FinancialAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderConfig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.UserGamification", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.UserMascotItem", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.Gamification.MascotItem", "MascotItem")
                        .WithMany()
                        .HasForeignKey("MascotItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MascotItem");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Gamification.UserMission", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.Gamification.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.GoalContribution", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.SavingGoal", "SavingGoal")
                        .WithMany("Contributions")
                        .HasForeignKey("SavingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingGoal");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.SavingGoal", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.SpendingInsight", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinMate.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMate.Domain.Entities.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinMate.Domain.Entities.NotificationLog", "NotificationLog")
                        .WithOne()
                        .HasForeignKey("FinMate.Domain.Entities.Transaction", "NotificationLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMate.Domain.Entities.SavingGoal", "SavingGoal")
                        .WithMany()
                        .HasForeignKey("SavingGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinMate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FinancialAccount");

                    b.Navigation("NotificationLog");

                    b.Navigation("SavingGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.User", b =>
                {
                    b.OwnsOne("FinMate.Domain.ValueObjects.NotificationPreferences", "NotificationPrefs", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("BudgetAlertsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("budget_alerts_enabled");

                            b1.Property<bool>("MissionRemindersEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("mission_reminders_enabled");

                            b1.Property<bool>("PushEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("push_enabled");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("NotificationPrefs")
                        .IsRequired();
                });

            modelBuilder.Entity("FinMate.Domain.Entities.Budget", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.NotificationLog", b =>
                {
                    b.Navigation("AiResult");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.SavingGoal", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("FinMate.Domain.Entities.User", b =>
                {
                    b.Navigation("FinancialAccounts");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
