<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FinMate.Domain\FinMate.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.*" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.*" />
  </ItemGroup>

</Project>
